### PR TITLE
2021 Updates

### PR DESCRIPTION
**Pull request by dcharatan**
The main changes:

* Changed the README formatting slightly and added a section about the mesh validator
* Updated Eigen
* Cleaned up `main.cpp`

### CODE REVIEW

**Comment by maggie1059** [comment]
Can we add Eigen to the .gitignore?

**Comment by dcharatan** [comment]
We definitely could add the Eigen files to the .gitignore and remove them from the repo, but then students would have to manually download and include them. I'm fine with doing it either way.

**Comment by dritchie** [comment]
Let's keep Eigen in the repo. It's nice to have the project be "self-contained" (i.e. no external dependencies)

**Comment by dcharatan** [comment]
Removed Eigen after more discussion on Slack

**Pull request merged**
